<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class WinningsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('winnings')->delete();
        
        \DB::table('winnings')->insert(array (
            0 => 
            array (
                'id' => 2,
                'game_id' => 19,
                'score' => 4,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 0,
                'status' => 'accepted',
            ),
            1 => 
            array (
                'id' => 3,
                'game_id' => 19,
                'score' => 8,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            2 => 
            array (
                'id' => 4,
                'game_id' => 19,
                'score' => 3,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            3 => 
            array (
                'id' => 5,
                'game_id' => 19,
                'score' => 4,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            4 => 
            array (
                'id' => 6,
                'game_id' => 19,
                'score' => 8,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            5 => 
            array (
                'id' => 7,
                'game_id' => 19,
                'score' => 4,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 0,
                'status' => 'accepted',
            ),
            6 => 
            array (
                'id' => 8,
                'game_id' => 19,
                'score' => 3,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 0,
                'status' => 'accepted',
            ),
            7 => 
            array (
                'id' => 9,
                'game_id' => 19,
                'score' => 3,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            8 => 
            array (
                'id' => 10,
                'game_id' => 19,
                'score' => 6,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            9 => 
            array (
                'id' => 11,
                'game_id' => 19,
                'score' => 5,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 0,
                'status' => 'accepted',
            ),
            10 => 
            array (
                'id' => 12,
                'game_id' => 19,
                'score' => 2,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            11 => 
            array (
                'id' => 13,
                'game_id' => 19,
                'score' => 9,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            12 => 
            array (
                'id' => 14,
                'game_id' => 19,
                'score' => 4,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            13 => 
            array (
                'id' => 15,
                'game_id' => 19,
                'score' => 9,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            14 => 
            array (
                'id' => 16,
                'game_id' => 19,
                'score' => 9,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            15 => 
            array (
                'id' => 17,
                'game_id' => 19,
                'score' => 9,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 0,
                'status' => 'accepted',
            ),
            16 => 
            array (
                'id' => 18,
                'game_id' => 19,
                'score' => 2,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            17 => 
            array (
                'id' => 19,
                'game_id' => 19,
                'score' => 5,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            18 => 
            array (
                'id' => 20,
                'game_id' => 19,
                'score' => 3,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 0,
                'status' => 'accepted',
            ),
            19 => 
            array (
                'id' => 21,
                'game_id' => 19,
                'score' => 3,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-01 10:47:38',
                'updated_at' => '2022-09-01 10:47:38',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            20 => 
            array (
                'id' => 22,
                'game_id' => 21,
                'score' => 4,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 3,
                'status' => 'accepted',
            ),
            21 => 
            array (
                'id' => 23,
                'game_id' => 21,
                'score' => 4,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            22 => 
            array (
                'id' => 24,
                'game_id' => 21,
                'score' => 5,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            23 => 
            array (
                'id' => 25,
                'game_id' => 21,
                'score' => 4,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            24 => 
            array (
                'id' => 26,
                'game_id' => 21,
                'score' => 4,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 3,
                'status' => 'accepted',
            ),
            25 => 
            array (
                'id' => 27,
                'game_id' => 21,
                'score' => 4,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 0,
                'status' => 'accepted',
            ),
            26 => 
            array (
                'id' => 28,
                'game_id' => 21,
                'score' => 5,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            27 => 
            array (
                'id' => 29,
                'game_id' => 21,
                'score' => 6,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 3,
                'status' => 'accepted',
            ),
            28 => 
            array (
                'id' => 30,
                'game_id' => 21,
                'score' => 6,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            29 => 
            array (
                'id' => 31,
                'game_id' => 21,
                'score' => 5,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 0,
                'status' => 'accepted',
            ),
            30 => 
            array (
                'id' => 32,
                'game_id' => 21,
                'score' => 6,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            31 => 
            array (
                'id' => 33,
                'game_id' => 21,
                'score' => 5,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            32 => 
            array (
                'id' => 34,
                'game_id' => 21,
                'score' => 6,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            33 => 
            array (
                'id' => 35,
                'game_id' => 21,
                'score' => 4,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 3,
                'status' => 'accepted',
            ),
            34 => 
            array (
                'id' => 36,
                'game_id' => 21,
                'score' => 5,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            35 => 
            array (
                'id' => 37,
                'game_id' => 21,
                'score' => 6,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 0,
                'status' => 'accepted',
            ),
            36 => 
            array (
                'id' => 38,
                'game_id' => 21,
                'score' => 5,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            37 => 
            array (
                'id' => 39,
                'game_id' => 21,
                'score' => 6,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            38 => 
            array (
                'id' => 40,
                'game_id' => 21,
                'score' => 4,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            39 => 
            array (
                'id' => 41,
                'game_id' => 21,
                'score' => 5,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 10:51:25',
                'updated_at' => '2022-09-01 10:51:25',
                'score_2' => 0,
                'status' => 'accepted',
            ),
            40 => 
            array (
                'id' => 42,
                'game_id' => 21,
                'score' => 6,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 11:04:20',
                'updated_at' => '2022-09-24 13:43:58',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            41 => 
            array (
                'id' => 43,
                'game_id' => 21,
                'score' => 6,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 11:04:20',
                'updated_at' => '2022-09-24 13:47:03',
                'score_2' => 3,
                'status' => 'accepted',
            ),
            42 => 
            array (
                'id' => 44,
                'game_id' => 21,
                'score' => 4,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 11:04:20',
                'updated_at' => '2022-09-24 13:52:02',
                'score_2' => 0,
                'status' => 'accepted',
            ),
            43 => 
            array (
                'id' => 45,
                'game_id' => 21,
                'score' => 6,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 11:04:20',
                'updated_at' => '2022-09-01 11:04:20',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            44 => 
            array (
                'id' => 46,
                'game_id' => 21,
                'score' => 6,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 11:04:20',
                'updated_at' => '2022-09-01 11:04:20',
                'score_2' => 0,
                'status' => 'accepted',
            ),
            45 => 
            array (
                'id' => 47,
                'game_id' => 21,
                'score' => 6,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 11:04:20',
                'updated_at' => '2022-09-01 11:04:20',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            46 => 
            array (
                'id' => 48,
                'game_id' => 21,
                'score' => 6,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 11:04:20',
                'updated_at' => '2022-09-01 11:04:20',
                'score_2' => 3,
                'status' => 'accepted',
            ),
            47 => 
            array (
                'id' => 49,
                'game_id' => 21,
                'score' => 5,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 11:04:20',
                'updated_at' => '2022-09-01 11:04:20',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            48 => 
            array (
                'id' => 50,
                'game_id' => 21,
                'score' => 4,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 11:04:20',
                'updated_at' => '2022-09-01 11:04:20',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            49 => 
            array (
                'id' => 51,
                'game_id' => 21,
                'score' => 5,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 11:04:20',
                'updated_at' => '2022-09-01 11:04:20',
                'score_2' => 3,
                'status' => 'accepted',
            ),
            50 => 
            array (
                'id' => 52,
                'game_id' => 21,
                'score' => 5,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 11:04:20',
                'updated_at' => '2022-09-01 11:04:20',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            51 => 
            array (
                'id' => 53,
                'game_id' => 21,
                'score' => 5,
                'winner_mail' => 'Paris@gmail.com',
                'winner_team' => 'Paris Basket',
                'created_at' => '2022-09-01 11:04:20',
                'updated_at' => '2022-09-01 11:04:20',
                'score_2' => 0,
                'status' => 'accepted',
            ),
            52 => 
            array (
                'id' => 129,
                'game_id' => 45,
                'score' => 4,
                'winner_mail' => 'jbull635@gmail.com',
                'winner_team' => 'Real Team',
                'created_at' => '2022-09-24 14:01:19',
                'updated_at' => '2022-09-24 14:03:19',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            53 => 
            array (
                'id' => 130,
                'game_id' => 48,
                'score' => 25,
                'winner_mail' => 'jbull635@gmail.com',
                'winner_team' => 'Team-De-Basket',
                'created_at' => '2022-09-29 13:19:00',
                'updated_at' => '2022-09-29 13:20:19',
                'score_2' => 18,
                'status' => 'accepted',
            ),
            54 => 
            array (
                'id' => 149,
                'game_id' => 50,
                'score' => 25,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal basket',
                'created_at' => '2022-09-29 13:40:30',
                'updated_at' => '2022-09-29 13:40:55',
                'score_2' => 100,
                'status' => 'accepted',
            ),
            55 => 
            array (
                'id' => 151,
                'game_id' => 51,
                'score' => 3,
                'winner_mail' => 'jbull635@gmail.com',
                'winner_team' => 'Real Team',
                'created_at' => '2022-09-29 13:43:54',
                'updated_at' => '2022-09-29 13:44:11',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            56 => 
            array (
                'id' => 152,
                'game_id' => 52,
                'score' => 4,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-09-30 09:08:58',
                'updated_at' => '2022-09-30 09:09:25',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            57 => 
            array (
                'id' => 153,
                'game_id' => 53,
                'score' => 5,
                'winner_mail' => 'jbull635@gmail.com',
                'winner_team' => 'Real Team',
                'created_at' => '2022-09-30 09:11:38',
                'updated_at' => '2022-09-30 09:12:05',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            58 => 
            array (
                'id' => 154,
                'game_id' => 54,
                'score' => 9,
                'winner_mail' => 'jbull635@gmail.com',
                'winner_team' => 'Team-De-Basket',
                'created_at' => '2022-09-30 09:40:04',
                'updated_at' => '2022-09-30 09:40:45',
                'score_2' => 10,
                'status' => 'accepted',
            ),
            59 => 
            array (
                'id' => 156,
                'game_id' => 56,
                'score' => 3,
                'winner_mail' => 'jbull635@gmail.com',
                'winner_team' => 'Real Team',
                'created_at' => '2022-10-01 19:42:58',
                'updated_at' => '2022-10-01 19:43:37',
                'score_2' => 1,
                'status' => 'accepted',
            ),
            60 => 
            array (
                'id' => 202,
                'game_id' => 101,
                'score' => 9,
                'winner_mail' => 'jbull635@gmail.com',
                'winner_team' => 'Real Team',
                'created_at' => '2022-10-06 08:38:52',
                'updated_at' => '2022-10-06 08:38:52',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            61 => 
            array (
                'id' => 204,
                'game_id' => 102,
                'score' => 6,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-10-06 08:54:24',
                'updated_at' => '2022-10-06 08:54:24',
                'score_2' => 0,
                'status' => 'accepted',
            ),
            62 => 
            array (
                'id' => 205,
                'game_id' => 103,
                'score' => 5,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-10-06 11:20:42',
                'updated_at' => '2022-10-06 11:20:42',
                'score_2' => 2,
                'status' => 'accepted',
            ),
            63 => 
            array (
                'id' => 206,
                'game_id' => 104,
                'score' => 4,
                'winner_mail' => 'Jamal@gmail.com',
                'winner_team' => 'Jamal Foot',
                'created_at' => '2022-10-06 11:21:16',
                'updated_at' => '2022-10-06 11:21:16',
                'score_2' => 0,
                'status' => 'accepted',
            ),
            64 => 
            array (
                'id' => 207,
                'game_id' => 105,
                'score' => 6,
                'winner_mail' => 'jbull635@gmail.com',
                'winner_team' => 'Real Team',
                'created_at' => '2022-10-06 11:25:55',
                'updated_at' => '2022-10-06 11:25:55',
                'score_2' => 3,
                'status' => 'accepted',
            ),
            65 => 
            array (
                'id' => 208,
                'game_id' => 106,
                'score' => 9,
                'winner_mail' => 'jbull635@gmail.com',
                'winner_team' => 'Real Team',
                'created_at' => '2022-10-06 11:26:27',
                'updated_at' => '2022-10-06 11:26:27',
                'score_2' => 1,
                'status' => 'accepted',
            ),
        ));
        
        
    }
}